apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.5.1
    replicas: 1
    listeners:
      - name: tls
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      # - name: ext
      #   port: 9093
      #   type: LoadBalancer
      #   tls: false
    authorization:
      type: simple
      superUsers:
        - CN=kafka
        - kafka
        - admin
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.3"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
