apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic my-topic using consumer group my-group
      - resource:
          type: topic
          name: tidepool
          patternType: prefix
        operations:
          - All 
        host: "*"
      - resource:
          type: group
          name: tidepool-kafka-cluster
          patternType: literal
        operations:
          - All
        host: "*"
      - resource:
          type: group
          name: tidepool-seagull
          patternType: literal
        operations:
          - All
        host: "*"
      - resource:
          type: group
          name: tidepool-messageapi
          patternType: literal
        operations:
          - All
        host: "*"
      - resource:
          type: group
          name: consumers
          patternType: literal
        operations:
          - All
        host: "*"
      - resource:
          type: group
          name: tidepool-mailer
          patternType: literal
        operations:
          - All
        host: "*"
      - resource:
          type: group
          name: tidepool-gatekeeper
          patternType: literal
        operations:
          - All
        host: "*"
